// Code generated by "stringer -type JSONType"; DO NOT EDIT.

package jsonparser_airp

import "strconv"

const _JSONType_name = "ErrorNullBoolNumberStringArrayObject"

var _JSONType_index = [...]uint8{0, 5, 9, 13, 19, 25, 30, 36}

func (i JSONType) String() string {
	if i >= JSONType(len(_JSONType_index)-1) {
		return "JSONType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JSONType_name[_JSONType_index[i]:_JSONType_index[i+1]]
}
